# Generated by Django 2.1.7 on 2020-01-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('action', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('scientificName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CultureParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('minValue', models.FloatField()),
                ('maxValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Culture')),
            ],
        ),
        migrations.CreateModel(
            name='DataMean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Culture')),
            ],
        ),
        migrations.CreateModel(
            name='NoeudCollecteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('topic', models.TextField()),
                ('status', models.IntegerField()),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noeudCollecteurs', to='Cultures.Culture')),
            ],
        ),
        migrations.CreateModel(
            name='NoeudMaitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('topic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledActuators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('repeatInterval', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('action', models.TextField()),
                ('noeudCollecteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuatorSchedule', to='Cultures.NoeudCollecteur')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('units', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='noeudcollecteur',
            name='noeudMaitre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noeudsCollecteurs', to='Cultures.NoeudMaitre'),
        ),
        migrations.AddField(
            model_name='noeudcollecteur',
            name='parameters',
            field=models.ManyToManyField(to='Cultures.CultureParameters'),
        ),
        migrations.AddField(
            model_name='datamean',
            name='valueType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Type'),
        ),
        migrations.AddField(
            model_name='data',
            name='noeudCollecteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.NoeudCollecteur'),
        ),
        migrations.AddField(
            model_name='data',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.CultureParameters'),
        ),
        migrations.AddField(
            model_name='cultureparameters',
            name='valueType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Type'),
        ),
        migrations.AddField(
            model_name='culture',
            name='parameters',
            field=models.ManyToManyField(to='Cultures.CultureParameters'),
        ),
        migrations.AddField(
            model_name='actuatorhistory',
            name='noeudCollecteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuatorHistory', to='Cultures.NoeudCollecteur'),
        ),
    ]
