# Generated by Django 2.2.5 on 2020-01-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gpsCoordinateX', models.FloatField()),
                ('gpsCoordinateY', models.FloatField()),
                ('status', models.IntegerField()),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('scientificName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CultureParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('minValue', models.FloatField()),
                ('maxValue', models.FloatField()),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Culture')),
            ],
        ),
        migrations.CreateModel(
            name='NoeudCollecteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NoeudMaitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('units', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpsCoordinateX', models.FloatField()),
                ('gpsCoordinateY', models.FloatField()),
                ('status', models.IntegerField()),
                ('Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Type')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Culture')),
                ('noeudCollecteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.NoeudCollecteur')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledActuators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('repeatInterval', models.IntegerField()),
                ('Timestamp', models.DateTimeField()),
                ('Actuator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Actuator')),
            ],
        ),
        migrations.CreateModel(
            name='ParamAttribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Culture')),
                ('cultureParameters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.CultureParameters')),
            ],
        ),
        migrations.AddField(
            model_name='noeudcollecteur',
            name='noeudMaitre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.NoeudMaitre'),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Culture')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Sensor')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Type')),
            ],
        ),
        migrations.AddField(
            model_name='cultureparameters',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Type'),
        ),
        migrations.CreateModel(
            name='ActuatorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('Actuator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Actuator')),
            ],
        ),
        migrations.AddField(
            model_name='actuator',
            name='NoeudCollecteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.NoeudCollecteur'),
        ),
    ]
