# Generated by Django 2.2.5 on 2020-01-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cultures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledactuators',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='NoeudCollecteur',
        ),
        migrations.RemoveField(
            model_name='scheduledactuators',
            name='Actuator',
        ),
        migrations.AddField(
            model_name='actuator',
            name='noeudCollecteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuators', to='Cultures.NoeudCollecteur'),
        ),
        migrations.AddField(
            model_name='scheduledactuators',
            name='actuator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled', to='Cultures.Actuator'),
        ),
        migrations.AlterField(
            model_name='actuatorhistory',
            name='Actuator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='Cultures.Actuator'),
        ),
        migrations.AlterField(
            model_name='noeudcollecteur',
            name='noeudMaitre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noeudsCollecteurs', to='Cultures.NoeudMaitre'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='Cultures.Culture'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='noeudCollecteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='Cultures.NoeudCollecteur'),
        ),
    ]
