# Generated by Django 2.2.5 on 2020-01-20 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cultures', '0002_auto_20200106_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='actuator',
            old_name='type',
            new_name='valueType',
        ),
        migrations.RenameField(
            model_name='cultureparameters',
            old_name='type',
            new_name='valueType',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='type',
            new_name='parameter',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='Type',
            new_name='valueType',
        ),
        migrations.RemoveField(
            model_name='cultureparameters',
            name='culture',
        ),
        migrations.AddField(
            model_name='culture',
            name='parameters',
            field=models.ManyToManyField(to='Cultures.CultureParameters'),
        ),
        migrations.AddField(
            model_name='noeudcollecteur',
            name='topic',
            field=models.TextField(default='/sensor/humidity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noeudmaitre',
            name='topic',
            field=models.TextField(default='sensor/humidty'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ParamAttribution',
        ),
        migrations.AddField(
            model_name='datamean',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Culture'),
        ),
        migrations.AddField(
            model_name='datamean',
            name='valueType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cultures.Type'),
        ),
    ]
